{% set name = "opentelemetry-propagator-gcp" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b5066851d55be13344985c895ea5f07809226c21de821d864e7ce60602487663

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.0

test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/main/opentelemetry-propagator-gcp
  summary: Google Cloud propagator for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
